repos:
  - repo: local
    hooks:
      - id: clang-format-all
        name: clang-format all C++ sources
        entry: bash .scripts/format.sh
        language: system
        pass_filenames: false
        always_run: true
      - id: include-guards
        name: check include guards
        entry: bash .scripts/check_include_guards.sh
        language: system
        pass_filenames: false
        files: \.hpp$
